# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6ac1e2780774b0f54d97f36800e73edc5567b0fa0d2267786476718ff7146b37fa90df22d0d06ba29e2f0345d7ca68ca315e169bcb68934c5d3e80c2dd7b549

test:
  secret_key_base: 5f33fb0f8d2c4966216fb2cbe5369e2654136e0a006c805b23fdd1fe951cb1ea033322f37eb496466990c50b86bdffdb81268e7b0ac770de50aebeefa650a0f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
